### ISSUE TITLE
您好，我是小白

### ISSUE THREAD

**Issue by oMhuAaN** [yz1311/rn-bugly#1]
我是用您这个好，还是react-native-bugly好？

**Comment by yz1311** [comment]
如果需要android升级可以用这个，如果只是统计，两者的区别不大

**Comment by oMhuAaN** [comment]
> 
> 
> 如果需要android升级可以用这个，如果只是统计，两者的区别不大

我只想使用bugly的全量包更新功能，之前react-native-bugly试了都不能跑起来。用了您的之后，终于跑起来了，您的文档比较清晰准确。
