### ISSUE TITLE
pod install 失败

### ISSUE THREAD

**Issue by FTD-ZF** [yz1311/rn-bugly#10]
[!] Error installing Bugly
[!] /usr/bin/curl -f -L -o /var/folders/rv/0pjrq01x2qb_cyf5bgt958xm0000gn/T/d20200804-3947-1apa58c/file.zip https://raw.githubusercontent.com/BuglyDevTeam/Bugly-iOS/master/release/Bugly-2.5.2.zip --create-dirs --netrc-optional --retry 2

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to raw.githubusercontent.com port 443: Connection refused

pod install 其他组件都是能成功的，就这个不行额，不知道咋回事

**Comment by yz1311** [comment]
这个是连接不上raw.githubusercontent.com这个地址

1.最好FQ或者改下host

2.你也可以在Podfile文件的第一行加一句试下，不确定是否有效
```
source 'https://cdn.cocoapods.org/'
```

3.还不行的，可以参考这种方式修改该库指向到其他位置，譬如gitee
![](https://tva1.sinaimg.cn/large/007S8ZIlgy1ghelu2tlv4j30n402bdfz.jpg)
[https://www.jianshu.com/p/29a09903d552](https://www.jianshu.com/p/29a09903d552)

**Comment by FTD-ZF** [comment]
[!] Error installing RNBugly
[!] /usr/bin/git clone https://github.com/yz1311/rn-bugly.git /var/folders/rv/0pjrq01x2qb_cyf5bgt958xm0000gn/T/d20200804-13922-m94mfe --template= --single-branch --depth 1 --branch v0.3.0

Cloning into '/var/folders/rv/0pjrq01x2qb_cyf5bgt958xm0000gn/T/d20200804-13922-m94mfe'...
warning: Could not find remote branch v0.3.0 to clone.
fatal: Remote branch v0.3.0 not found in upstream origin

==========================

在Podfile中，直接加入这个 pod 'RNBugly', :podspec => '../node_modules/rn-bugly/'

发现 Bugly 有了 但是RNBugly还是不能install成功，说是没有这个0.3.0的分支；

还有就是这个example的项目的Podfile中没有引入bugly的相关路径也能pod install成功RNBugly，是怎么操作的

**Comment by yz1311** [comment]
RN0.60版本引入了[auto linking](https://github.com/react-native-community/cli/blob/master/docs/autolinking.md)的机制，在Podfile中不用手动添加相关库的代码段，只要库中带有xxx..podspec文件就会被自动添加.

上面的安装错误，没遇到这个报错过，我创建了一个`v0.3.0`的分支，希望有帮助
