### ISSUE TITLE
在模拟器上可以，但是在安卓真机上不显示更新，为什么？

### ISSUE THREAD

**Issue by xiaoketeng** [yz1311/rn-bugly#12]
我的安卓手机app是V1.0版本
我上传到bugly官网的apk版本是V3.0
react-native:0.63.2
rn-bugly: 0.3.0
相关文件配置如下：
项目/android/build.gradle
`    defaultConfig {
        applicationId "com.app_baise"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 3
        versionName "3.0"
        multiDexEnabled true
    }`
项目/android/app/src/main/java/com/app_baise/MainApplication.java
`import com.reactlibrary.bugly.RNBuglyModule;

  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
    initializeFlipper(this, getReactNativeHost().getReactInstanceManager());
    //仅仅初始化(推荐使用该方法，所有的检查更新触发都都js端，更加灵活)
    RNBuglyModule.initWithoutAutoCheckUpgrade(getApplicationContext(), "1*******7", false);
  }
`
项目//app/App.js
`import RNBugly from 'rn-bugly';
  useEffect(() => {
    if (Platform.OS === 'android') {
      // bugly检查热更新
      setTimeout(() => {
        RNBugly.checkUpgrade({
          isManual: false,
          isSilence: false,
        });
      }, 3000);
    }
    syncData('homeMenuStorage','home/initHomeMenu',homeMenuDefault);
    BackHandler.addEventListener('hardwareBackPress', onBackAndroid);
    syncData('GMenuStorage','gAffairsOpen/initGMenu',gMenuDefault);
    return ()=>{
      BackHandler.removeEventListener('hardwareBackPress', onBackAndroid);
    }
  });
`

**Comment by yz1311** [comment]
是不是没有兼容http? 在注意事项第2条有说明

**Comment by xiaoketeng** [comment]
我知道什么原因了，不是http的原因，谢谢你的回复
