### ISSUE TITLE
Android端更新弹出框样式

### ISSUE THREAD

**Issue by skylarklxlong** [yz1311/rn-bugly#13]
您好，请问能否自定义Android端弹出框样式？

之前单独在安卓端使用bugly时可以通过如下方式设置自定义升级对话框样式
Beta.upgradeDialogLayoutId = R.layout.layout_app_update_dialog;

**Comment by yz1311** [comment]
原生端的修改，这些代码依旧可以在原生去写
不知道你需要的是哪种情况？
1.如果只是需要更改一个默认的样式，直接在原生端改就行了
2.需要在js端去动态设置原生端写好的布局(譬如原生写好了R.layout.layout_app_update_dialog1、R.layout.layout_app_update_dialog2、R.layout.layout_app_update_dialog3三种界面)，然后根据情况去动态显示不同的布局，这个倒是可以实现，根据资源名称获取id然后设置就行了，要改库，感觉意义不大
3.在js端完全自定义，其实可以完全自己写一套js端的界面，不过后续的下载和安装由于bugly没有暴露相关的接口，所以需要自己去写，用这个库的意义不大了

如果只是一些简单的弹窗样式，bugly的后台有支持的
![image](https://user-images.githubusercontent.com/9854019/104887974-1748f580-59a7-11eb-98de-0c1bc730f365.png)

**Comment by skylarklxlong** [comment]
> 原生端的修改，这些代码依旧可以在原生去写
> 
> 不知道你需要的是哪种情况？
> 
> 1.如果只是需要更改一个默认的样式，直接在原生端改就行了
> 
> 2.需要在js端去动态设置原生端写好的布局(譬如原生写好了R.layout.layout_app_update_dialog1、R.layout.layout_app_update_dialog2、R.layout.layout_app_update_dialog3三种界面)，然后根据情况去动态显示不同的布局，这个倒是可以实现，根据资源名称获取id然后设置就行了，要改库，感觉意义不大
> 
> 3.在js端完全自定义，其实可以完全自己写一套js端的界面，不过后续的下载和安装由于bugly没有暴露相关的接口，所以需要自己去写，用这个库的意义不大了
> 
> 如果只是一些简单的弹窗样式，bugly的后台有支持的
> ![image](https://user-images.githubusercontent.com/9854019/104887974-1748f580-59a7-11eb-98de-0c1bc730f365.png)

好的，多谢，我直接在原生端搞
