### ISSUE TITLE
最新版有bug

### ISSUE THREAD

**Issue by skylarklxlong** [yz1311/rn-bugly#17]
`    closeCrashReport: function () {
        RNBugly.closeCrashReport();
    },
`

`RCT_EXPORT_METHOD(closeCrashReport)
{
    [Bugly closeCrashReport];
}
`

iOS端并未实现该方法，需增加对平台的的判断

**Comment by yz1311** [comment]
是编译报错是吧？
是的话，应该是本地的bugly sdk版本导致的，这个接口是最近几个版本才加的，你需要更新下cocopods仓库才行
```
pod repo update
```
![](https://tva1.sinaimg.cn/large/008eGmZEgy1gpgqpdr5a2j30h00chaat.jpg)

我还是固定一下两端的sdk版本号，避免出现这个情况，感谢反馈

**Comment by skylarklxlong** [comment]
> 是编译报错是吧？
> 是的话，应该是本地的bugly sdk版本导致的，这个接口是最近几个版本才加的，你需要更新下cocopods仓库才行
> 
> ```
> pod repo update
> ```
> 
> ![](https://camo.githubusercontent.com/a14b879569657bf40f3cc4e70c5c014f7ca6ffed967f17d161c3b0a03da861dc/68747470733a2f2f747661312e73696e61696d672e636e2f6c617267652f30303865476d5a45677931677067717064723561326a333068303063686161742e6a7067)
> 
> 我还是固定一下两端的sdk版本号，避免出现这个情况，感谢反馈

好的，谢谢

**Comment by yz1311** [comment]
方便的话，可以试下0.3.3-beta1  ,然后`pod install`的时候应该会提示你升级库

**Comment by skylarklxlong** [comment]
> 方便的话，可以试下0.3.3-beta1 ,然后`pod install`的时候应该会提示你升级库

好，我来试试看

**Comment by yz1311** [comment]
0.3.3-beta2.，我刚在双端试了下，是可以的

**Comment by skylarklxlong** [comment]
> 0.3.3-beta2.，我刚在双端试了下，是可以的

我试了是可以的
