### ISSUE TITLE
安装后一打开就闪退了，

### ISSUE THREAD

**Issue by oMhuAaN** [yz1311/rn-bugly#3]
![图片](https://user-images.githubusercontent.com/24907600/71724506-78b92780-2e6b-11ea-80dc-529b86ceb8df.png)

**Comment by yz1311** [comment]
麻烦用logcat看下报错信息

**Comment by yz1311** [comment]
debug下不报错，就release下报错了？

**Comment by oMhuAaN** [comment]
debug下也报错，所以我加了一个判断，加了就不报错了。

**Comment by oMhuAaN** [comment]
![图片](https://user-images.githubusercontent.com/24907600/71724860-cf733100-2e6c-11ea-91fa-554ee352364e.png)
像这样没有判断也是报错的

**Comment by oMhuAaN** [comment]
![图片](https://user-images.githubusercontent.com/24907600/71724908-fc274880-2e6c-11ea-8c89-657f48b2addc.png)
报错如图

**Comment by oMhuAaN** [comment]
logcat没用过，需要点时间研究

**Comment by oMhuAaN** [comment]
大佬，您下班了吗

**Comment by yz1311** [comment]
export function checkUpgrade (params:{isManual?: boolean,isSilence?: boolean}): void

这个用法是传递第一个参数是一个对象，里面有isManual和isSilence两个可选属性

你应该没用typescript，不然你那样写会直接报错的

**Comment by oMhuAaN** [comment]
是的，没用typescript，我现在要怎么办？

**Comment by yz1311** [comment]
.checkUpgrade ({isManual: true,isSilence: true})
这样传值

**Comment by oMhuAaN** [comment]
非常感谢，我对您的景仰有如滔滔江水，连绵不绝，又如黄河泛滥，一发而不可收拾，听阁下一言，胜读十年寒窗，
