### ISSUE TITLE
rn bugly 不能使用

### ISSUE THREAD

**Issue by samkk** [yz1311/rn-bugly#4]
RT：我安卓打了一个debug包，在bugly上传了一个高版本的apk

本地一直提示是 最新版本。
需要什么姿势嘛？

**Comment by samkk** [comment]
Bugly.init(getApplicationContext(), "注册时申请的APPID", false);
要使用appid 不是appkey

**Comment by yz1311** [comment]
不好意思，最近有点忙，我那个描述有问题，请问改成appId后可以了吗?

**Comment by samkk** [comment]
嗯嗯，对，可以正常使用了

**Comment by yz1311** [comment]
新版本发布了，文档已更新
