### ISSUE TITLE
非常感谢作者开源，有运营数据了 ，但全量升级功能不起作用。

### ISSUE THREAD

**Issue by vanxv** [yz1311/rn-bugly#5]
安装好系统，
有运营数据了 ，但全量升级功能不起作用。

app新版已放到bugly系统上。
获取升级数据时，返回的内容是null

```
RNBugly.checkUpgrade({
        //该值为true的时候，会有toast提示，如果不需要提示，设置为false
        isManual: true,
        isSilence: false
      });


let updateInfo = await RNBugly.getUpgradeInfo();
console.log(updateInfo)
null
```

**Comment by yz1311** [comment]
在logcat看下是否有bugly相关的日志,或者直接android原生调试,这种是最方便的

检查下一下几个方面:
1.上传的新版的versionCode是否大于本地的
2.如果targetSdkVersion>=28,检查是否支持http,这个在readme中有说明
3.改为直接原生初始化并且自动检查更新试试

**Comment by 349989153** [comment]
我碰到的问题是：
Didn't find class "com.tencent.tinker.entry.DefaultApplicationLike"

解决是：
在android/app/build.gradle的dependencies里面加一行：
implementation 'com.tencent.tinker:tinker-android-lib:1.9.9'

顺便：非常感谢作者大大写了这么个包，方便大家！

**Comment by 349989153** [comment]
@vanxv 另外在bugly后台发了更新之后，点击“启动”了吗

**Comment by yz1311** [comment]
`状态与操作`下面应该是绿色文字的`已启动`

![](https://tva1.sinaimg.cn/large/007S8ZIlgy1gfhjcp8j0sj306102u746.jpg)

**Comment by vanxv** [comment]
> @vanxv 另外在bugly后台发了更新之后，点击“启动”了吗

非常感谢回复，启动了，过2天折腾，最近在忙上线。等用户进来再改bug
