### ISSUE TITLE
安卓文档配置与 DEMO 不一致

### ISSUE THREAD

**Issue by orzhtml** [yz1311/rn-bugly#8]
DEMO：

MainApplication.java

import com.tencent.bugly.Bugly;

Bugly.init(getApplicationContext(),"b338692163",false);

**Comment by yz1311** [comment]
RNBuglyModule只是对Bugly的简单封装，是为了解决手动集成时app/build.gradle中dependencies的 implementation/compile的差异性问题

auto linking时直接用Bugly也是可以的，为了避免误会，我后面会将demo改为跟文档一致，谢谢反馈!
