### ISSUE TITLE
请问想使用异常上报和统计功能的话怎么初始化？

### ISSUE THREAD

**Issue by sam694260665** [yz1311/rn-bugly#9]
安卓那边的已经都根据read.me配置好了 Js代码那块没有改动 发现安装后 运营统计数据没有变化还是0

**Comment by yz1311** [comment]
1.确保appid正确
2调用根据文档调用原生的初始化方法
3.如果targetSdkVersion是28及以上，可以试下兼容http(这块文档下面有说明，是针对自动升级，可能统计的url也是http，导致无法访问服务器，如果1 2确定，那3的可能性很大)

**Comment by sam694260665** [comment]
> 1.确保appid正确
> 2调用根据文档调用原生的初始化方法
> 3.如果targetSdkVersion是28及以上，可以试下兼容http(这块文档下面有说明，是针对自动升级，可能统计的url也是http，导致无法访问服务器，如果1 2确定，那3的可能性很大)

谢谢 今天看 已经有数据了 可能是有延迟的原因 (时间还有点久 不知道是不是正常的)感谢开源~
